name: app deploy
on:
  push:
    paths:
      - "html/index.php"
      - "Dockerfile"

jobs:
  build-and-push:
    runs-on: self-hosted   #  your server runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        #run: docker build -t desi-php:${{ github.run_number }} .
        run: docker build -t desi-php:0.02 .

      # Login to Docker Hub (or GitHub Container Registry)
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push image
        run: |
          docker tag desi-php:0.02 desradeva/desi-php-web-server:0.02
          docker push desradeva/desi-php-web-server:0.02
          # docker tag desi-php:${{ github.run_number }} desradeva/desi-php-web-server:latest
          # docker push desradeva/desi-php-web-server:latest

